[package]
name = "kibi"
version = "0.2.0"
authors = ["Ila√Ø Deutel"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "A text editor in less than 1024 lines of code with syntax higlighting, search and more."
repository = "https://github.com/ilai-deutel/kibi"
readme = "README.md"
keywords = ["editor", "terminal", "text-editor"]
categories = ["text-editors", "development-tools"]
include = ["src/**/*", "Cargo.toml", "LICENSE*", "COPYRIGHT"]

[dependencies]
unicode-width = "0.1.8"

[target.'cfg(unix)'.dependencies]
libc = "0.2.76"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", default-features = false, features = ["wincon"] }
winapi-util = "0.1.4"

[dev-dependencies]
tempfile = "3.1.0"
serial_test = "0.5.0"

[badges]
travis-ci = { repository = "ilai-deutel/kibi", branch = "master" }
maintenance = { status = "actively-developed" }
