version = 1

[[annotations]]
path = [
    "**.rs",
    "**/.gitignore",
    "**/Cargo.toml",
    ".allstar/*.yaml",
    ".cargo/config.toml",
    ".github/CODEOWNERS",
    ".github/**.yml",
    ".vscode/settings.json",
    "assets/recording.cast",
    "assets/*.png",
    "assets/*.webm",
    "ci/*",
    "scripts/*",
    "syntax.d/*.ini",
    ".all-contributorsrc",
    ".markdownlint.json",
    "Cargo.lock",
    "COPYRIGHT",
    "clippy.toml",
    "config_example.ini",
    "deny.toml",
    "kibi.desktop",
    "rustfmt.toml",
]
SPDX-FileCopyrightText = "2020 Ila√Ø Deutel & Kibi Contributors"
SPDX-License-Identifier = "MIT or Apache-2.0"
